name: 'Netbird connect'
description: 'Connect your workflow to your Netbird network'
inputs:
  setup-key:
    description: 'Setup key obtained from the Management Service Dashboard (used to register peer)'
    required: true
  hostname:
    description: 'Sets a custom hostname that is visible from Netbird Dashboard'
    required: false
    default: ''
  management-url:
    description: 'Management Service URL [http|https]://[host]:[port] (default "https://api.netbird.io:443")'
    required: false
    default: 'https://api.netbird.io:443'
  args:
    description: 'Optional additional arguments to `netbird up`'
    required: false
    default: ''
branding:
  icon: 'bar-chart'
  color: 'orange'
runs:
  using: 'composite'
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' && runner.os != 'Windows' }}
      shell: bash
      run: |
        echo "::error title=error hint::Support Linux and Windows Only"
        exit 1
    - name: Download Netbird (Linux)
      if: runner.os == 'Linux'
      shell: bash
      env:
        USE_BIN_INSTALL: true
      run: curl -fsSL https://pkgs.netbird.io/install.sh | sh
    - name: Download Netbird (Windows)
      if: runner.os == 'Windows'
      shell: PowerShell
      run: |
        $msiPath = "$env:TEMP\netbird_installer.msi"
        Invoke-WebRequest -Uri "https://pkgs.netbird.io/windows/msi/x64" -OutFile $msiPath
        Start-Process msiexec.exe -Wait -ArgumentList "/i $msiPath AUTOSTART=0 /quiet"
        "C:\Program Files\NetBird" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Connect to Netbird
      shell: bash
      env:
        SETUP_KEY: ${{ inputs.setup-key }}
        ADDITIONAL_ARGS: ${{ inputs.args }}
        HOSTNAME: ${{ inputs.hostname }}
        MANAGEMENT_URL: ${{ inputs.management-url }}
      run: |
        if [ -z "${HOSTNAME}" ]; then
          HOSTNAME="github-$(hostname)"
        fi

        SUDO=""
        if [ "$RUNNER_OS" == "Linux" ]; then
          SUDO="sudo"
        fi

        $SUDO netbird up --setup-key=${SETUP_KEY} --hostname=${HOSTNAME} --management-url=${MANAGEMENT_URL} ${ADDITIONAL_ARGS}
    - name: Wait for Netbird to connect
      shell: bash
      run: |
        SUDO=""
        if [ "$RUNNER_OS" == "Linux" ]; then
          SUDO="sudo"
        fi
        
        while [ -z "$($SUDO netbird status | grep 'Management: Connected')" ]; do
          echo "Waiting for Netbird to connect..."
          sleep 5
        done